FROM node:20-alpine as builder

WORKDIR /app/client

COPY package*.json ./


# Install dependencies
RUN npm install

COPY . .

# Build the React app
RUN npm run build

## Final Image
FROM nginx

WORKDIR /usr/share/nginx/html

# Copy React build to Nginx
COPY --from=builder /app/client/build /usr/share/nginx/html

# Set permissions
RUN chown -R nginx:nginx /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
