#version: "3.8"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.dev
    environment:
      - REACT_APP_PORT=5173
      - CHOKIDAR_USEPOLLING=true
    image: client
    command: npm run dev -- --host 0.0.0.0
    restart: "no"
    stdin_open: true
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    image: server
    environment:
      - MONGO_URL=mongodb://app-db-1:27017/Alumni
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./server:/app/server
    restart: "no"

  db:
    image: mongo:4.4
    restart: "no"





