#version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.staging
    image: localhost:5000/client:staging
    ports:
      - "5173:80"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://server:3001

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.staging
    networks:
      - mern_network
    image: localhost:5000/server:staging
    environment:
       MONGO_URL: mongodb://mongodb:27017/Alumni
       PORT : 3001
       NODE_ENV: production
    command: node index.js
    depends_on:
      - db
    
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - db_staging:/data/db
    networks:
      - mern_network  # Keep the reference to the 'default' network here

volumes:
  db_staging:
    driver: local

