
services:
  client:
    image: localhost:5000/client:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "5173:80"
    stdin_open: true

  server:
    image: localhost:5000/server:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
     #environment:
       #- MONGO_URI=mongodb://db:27017/db
       #- PORT=4000
       #- NODE_ENV=production
    command: node index.js

  db:
    image: localhost:5000/db:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
     #environment:
    #   MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
    #   MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - db_prod:/data/Alumni

volumes:
  db_prod:
