version: "3.8"

networks:
  default:
    external:
      name: ops_default  # Make sure the external network is named correctly

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.staging
    image: localhost:5000/client:staging
    ports:
      - "5173:80"
    stdin_open: true
    networks:
      - default  # Ensure the client is connected to the same network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.staging
      args:
        MONGO_URL: mongodb://db:27017/Alumni  # Use service name 'db' instead of 'app-db-1'
        PORT: 3001
        NODE_ENV: production
    image: localhost:5000/server:staging
    environment:
      - MONGO_URL=mongodb://db:27017/Alumni  # Ensure no extra space before the URL
      - PORT=3001
      - NODE_ENV=production
    command: node index.js
    depends_on:
      - db  # Ensure 'server' starts after 'db'
    networks:
      - default  # Ensure 'server' is connected to the same network as 'db'

  db:
    image: mongo:4.4
    volumes:
      - db_staging:/data/Alumni
    networks:
      - default  # Ensure 'db' is connected to the same network as 'server'

volumes:
  db_staging:

