#version: "3.8"

networks:
  default:
     external:
        name: ops_default  # Make sure the external network is named correctly

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.staging
    image: localhost:5000/client:staging
    ports:
      - "5173:80"
    stdin_open: true
    networks:
      - default  # Keep the reference to the 'default' network here

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.staging
      args:
        MONGO_URI: mongodb://db:27017/Alumni
        PORT: 3001
        NODE_ENV: production
    image: localhost:5000/server:staging
    environment:
      - MONGO_URI=mongodb://db:27017/Alumni
      - PORT=4000
      - NODE_ENV=production
    command: node index.js
    depends_on:
      - db
    networks:
      - default  # Keep the reference to the 'default' network here
  db:
    image: mongo:4.4
    volumes:
      - db_staging:/data/Alumni
    networks:
      - default  # Keep the reference to the 'default' network here

volumes:
  db_staging:

