#version: "3.8"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client.dev
    environment:
      - REACT_APP_PORT=5173
      - CHOKIDAR_USEPOLLING=true
    image: client
    command: npm run dev
    restart: "no"
    stdin_open: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server.dev
    image: server
    environment:
      - MONGO_URI=$MONGO_URI
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
    volumes:
      - ./server:/app/server
    restart: "no"

  db:
    image: mongo:4.4
    restart: "no"
