#version: '3.8'

services:

  gogs:
    image: gogs/gogs

    ports:
      - "10022:22"
      - "9001:9001"


    volumes:
      - gogs:/data

  registry:
    image: registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry


  prometheus:
    image: prom/prometheus:v2.20.1
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - ./var/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

    depends_on:
      - cadvisor
    networks:
      - overlay_network
      - default

  grafana:
    image: grafana/grafana
    ports:
      - 7070:3000
    volumes:
      - ./var/grafana/grafana_data:/var/lib/grafana
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafanasecret
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - overlay_network
      - default

  cadvisor:
    image: google/cadvisor
    ports:
      - 5050:8080


    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


volumes:
  gogs: {}

  registry: {}

networks:
  overlay_network:
    driver: overlay
    attachable: true
  
